### ISSUE TITLE
Regex in controller.php causes an error with PHP 7.4

### ISSUE THREAD

**Issue by abhlabs** [taniarascia/laconia#22]
This really isn't an "issue" since laconia was developed for PHP 7.2, but this might help anyone considering a PHP update.

In controller.php, function validateUsername, the preg_match fails with error “Compilation failed: invalid range in character class at offset 10” after upgrading to PHP 7.4.  This appears to be caused by the update made in PHP’s implementation of PRCE2 (introduced in 7.3) that assumes the use of a dash in a character class defines a range.  For the regex in controller.php, the 3rd dash isn’t a range, it’s a literal, so I believe the simple, backwards compatible solution is to simply escape it.  I.e., instead of

`if (!preg_match("/^[a-zA-Z\d-_]+$/i", $username)) {`

change it to:

`if (!preg_match("/^[a-zA-Z\d\-_]+$/i", $username)) {`

**Comment by taniarascia** [comment]
Thanks for the note (and sorry for the delay). I updated the code.
