### ISSUE TITLE
Write some unit tests using PHPUnit

### ISSUE THREAD

**Issue by halfer** [taniarascia/laconia#5]
I can expand on this once the existing tickets are done - it's a "level up" target for now! :smile_cat: 

I tend to install PHPUnit and Mockery together for this purpose. Mockery has a fluent interface to create different kinds of class mocks i.e. fake secondary classes that we can rely upon when testing a class in isolation. I believe PHPUnit has its own mocking system, but I've learned Mockery instead, and this route seems to be popular with other PHP devs.

**Comment by taniarascia** [comment]
I added a `/tests` directory with a single HelloWorld test for future testing. I haven't used PHP Unit or TDD before, but it's all ready for future tests now.

**Comment by kevin-schmitt** [comment]
Hello,
In readme we can read "A modern MVC framework written without libraries or frameworks (PHP)."  phpunit is a librairie, so need change readme please. Create dir with functional test and other for unit test. For functional test i recommend [http://behat.org/en/latest/index.html](url)

**Comment by halfer** [comment]
135 stars! :star: Great achievement, Tania. :+1: 

Are you still maintaining this project? I could raise a PR with an example PHPUnit test, if that is of interest.

**Comment by taniarascia** [comment]
It is of interest! And yes, I’ve just made some nice UI updates and fixed a few issues.

**Comment by kevin-schmitt** [comment]
Best practice is for each pull request add test that check modifications. It's possible to update Readme file, part of contributing with that notion please?
