### ISSUE TITLE
Integrate docker compose 

### ISSUE THREAD

**Issue by kevin-schmitt** [taniarascia/laconia#7]
I think is will be interesting to integrate docker compose file, for easy install and upgrade environment.

**Comment by taniarascia** [comment]
If you end up making one, please submit a PR! If not, I'll try to get to it soon.

**Comment by kevin-schmitt** [comment]
Please can you fix conflict with PR [https://github.com/taniarascia/laconia/pull/8](https://github.com/taniarascia/laconia/pull/8)   Thanks :)

**Comment by jjmpsp** [comment]
+1 this would be very handy!

**Comment by taniarascia** [comment]
Docker compose is implemented, but user profile page and edit page list don't work properly yet due to apache->nginx rewrite considerations.

**Comment by taniarascia** [comment]
Thanks @kevin-schmitt for your help in getting this together!

**Comment by jjmpsp** [comment]
> Thanks @kevin-schmitt for your help in getting this together!

Good job!

@taniarascia do you need any help with fixing the nginx rewrite issues?

**Comment by kevin-schmitt** [comment]
@taniarascia @jjmpsp  I push one PR for clean some files. For problem 
>  apache->nginx rewrite considerations.

Can you open new issue @taniarascia @jjmpsp for this? problem is configuration file for nginx

 I think we have to try_files directive like [https://github.com/guillaumebriday/laravel-blog/blob/master/.cloud/nginx/nginx.conf](url) 

Thanks

**Comment by taniarascia** [comment]
@jjmpsp Yes, would definitely appreciate some insight there! I tried a couple of things, but nothing worked yet...

**Comment by kevin-schmitt** [comment]
Hello everyone,

I push a new PR #14  for problem routing, can you review my code and test please?
Thanks

**Comment by taniarascia** [comment]
I'm going to close this one and make a new issue for the Apache/Nginx issue.
